; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

#Include %A_ScriptDir%\Lib\ControlColor.ahk
#Include %A_ScriptDir%\Lib\Chrome\Chrome.ahk

Gui +hWndhMainWnd
Gui Color, White
ControlColor(hTxt, hMainWnd, 0xFFFFFF)
Gui, Add, Text,, 먼저 시청할 영상 주소를 입력하세요
Gui, Add, Edit, vUrl

Gui Add, Button, gBtnF vbtnFile, 시작하기

Gui Show, w392 h110, BJcreen

global pring := false
global SelectedFile := ""
global mode := 0


return 

BtnF: 
   Run, C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   Sleep, 1500
   
   Send, {Ctrl}
   Send, {Shift Down}{Ctrl Down}N ~ {Ctrl Up}{Shift Up}
   Send, https://www.youtube.com
   
   Sleep, 1000
   Send, {Enter}
   
   WinGet, WinStatus, MinMax, ahk_exe chrome.exe
   Sleep, 1000
   
   if (WinStatus != 0)
   WinRestore, ahk_exe chrome.exe
   
   Sleep, 1000
   WinMove, ahk_exe chrome.exe,, 0, 0, 1200, %A_ScreenHeight%
   WinMove, ahk_exe Vysor.exe,, 1200, 0, , %A_ScreenHeight%
   
   ;MouseMove, 1276, 504
   ;MouseClick
return 
		
