; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

#Include %A_ScriptDir%\Lib\ControlColor.ahk
#Include %A_ScriptDir%\Lib\Chrome\Chrome.ahk

Gui +hWndhMainWnd
Gui Color, White
ControlColor(hTxt, hMainWnd, 0xFFFFFF)
Gui Add, Button, x059 y90 w250 h28 gBtnF vbtnFile, CallChrome
Gui Add, Text, x059 y15 w55 h23 +0x200 vtxt1, StartURL
Gui Add, Text, x059 y40 w55 h23 +0x200 vtxt2, 검색어
Gui Add, Text, x059 y65 w55 h23 +0x200 vtxt3, 반복횟수

Gui Add, Edit, x120 y15 w175 h21 vinput1 
Gui Add, Edit, x120 y40 w175 h21 vinput2  
Gui Add, Edit, x120 y65 w175 h21 vinput3 
Gui Show, w392 h150, BJcreen

global pring := false
global SelectedFile := ""
global mode := 0


return 

BtnF:

   GuiControlGet, input1
   GuiControlGet, input2
   GuiControlGet, input3
   
   ChromeInst := new Chrome("ChromeProfile", "--app=" path, "--window-size=970,1000")
   
   if !(PageInst := ChromeInst.GetPage())
   {
      MsgBox, Could not retrieve page!
      ChromeInst.Kill()
   }
   else
   {
	
	PageInst.Call("Page.navigate", {"url": input1})
	Sleep, 500
	
	RootNode := PageInst.Call("DOM.getDocument").root
	Sleep, 1000

	urlStr := "$('.ytp-time-duration').innerHTML"
	ytptime := PageInst.Evaluate(urlStr).value
	ytptime := StrSplit(ytptime, ":")
	Loop % ytptime.MaxIndex(){
	  now_time := ytptime[A_Index]
	  ;MsgBox, %A_Index%번쨰 시간은 %now_time%
	  timecnt++
	} 
	;MsgBox, %timecnt%
	
	if(timecnt == 2){
	  ytptime[1] := ytptime[1] * 60
	  totalcnt := ytptime[1] + ytptime[2]
	} else if(timecnt == 3){
	  ytptime[2] := ytptime[2] * 60
	  ytptime[1] := ytptime[1] * 3600
	  totalcnt := ytptime[1] + ytptime[2] + ytptime[3]
	} else{
	  totalcnt := ytptime[1]
	}
	totalcnt := totalcnt * 1000
	totalcnt := totalcnt / 2
	
	

	WinGet, WinStatus, MinMax, ahk_exe chrome.exe
	Sleep, 1000
	
	if (WinStatus != 0)
	WinRestore, ahk_exe chrome.exe
	Sleep, 1000
	WinMove, ahk_exe chrome.exe,, 0, 0, 1200, %A_ScreenHeight%
	WinMove, ahk_exe Vysor.exe,, 1200, 0, , %A_ScreenHeight%
	
	
	;isAd = document.querySelectorAll(".ytp-ad-preview-container").length
	
	;urlStr := "$('.ytp-large-play-button')"
	;PlayBtn := PageInst.Evaluate(urlStr).value
	;if(PlayBtn = ){
	;PageInst.Evaluate("$('.ytp-large-play-button').click()")
	;}
	
	Sleep, 500
	  
	
	MouseClick, Left, 585, 536
	Sleep, 300
	MouseClick, Left, 655, 391
	Sleep, 300
	Send, {Down}{Down}{Down}{Down}{Enter}
	Sleep, %totalcnt%
	
	;2번째 영상 재생
	MouseClick, Left, 407, 109
	Send, %input2%{Enter}
	Sleep, 1000
	MouseClick, Left, 265, 522
	Sleep, 2000
	
	
	MouseClick, Left, 1266, 498
	
	Sleep, 1500
	MouseClick, Left, 1266, 498
	;MsgBox, %totalcnt%
   }
   
   
log_up(msg){
   
    log_path := A_ScriptDir "\log2.txt" 
    FileAppend, [%A_Mon%/%A_Mday% %A_Hour%:%A_Min%:%A_Sec%][%msg%]`n, %log_path%
    return
}
      
timeCalculate(){
    
	
}
return 
      