; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

#Include %A_ScriptDir%\Lib\ControlColor.ahk
#Include %A_ScriptDir%\Lib\Chrome\Chrome.ahk

Gui +hWndhMainWnd
Gui Color, White
ControlColor(hTxt, hMainWnd, 0xFFFFFF)
Gui Add, Button, x089 y15 w250 h28 gBtnF vbtnFile, CallChrome

Gui Show, w392 h110, BJcreen

global pring := false
global SelectedFile := ""
global mode := 0


return 

BtnF: 
6
   Run, chrome.exe "http://www.naver.com"
   Sleep, 1500
   
   WinGet, WinStatus, MinMax, ahk_exe chrome.exe
   Sleep, 1500
   
   if (WinStatus != 0)
   WinRestore, ahk_exe chrome.exe
   Sleep, 1500
   WinMove, ahk_exe chrome.exe,, 50, 50, 200, 600
		
return 
		
